# This is a basic workflow to help you get started with Actions

name: run Query

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 4/6 * * *'
  watch:
    types: started
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: '执行Query'
        env:
          QYWX: ${{ secrets.QYWX }}
          UID: ${{ secrets.UID }}
        run: python ./Query.py
